### PR TITLE
enable electron database encryption

### PR DESCRIPTION
**Pull request by beligatclement**

### CODE REVIEW

**Comment by jepiqueau** [comment]
@beligatclement i will look at it when i am back home 3 weeks times from now. Have you test it on Windows and package it without problem. This is the reason why i removed the feature some times ago.

**Comment by beligatclement** [comment]
@jepiqueau I'll focus on testing next week. When you talk about "package it without problem", you mean the plugin or the electron app ?

**Comment by jepiqueau** [comment]
@beligatclement i mean the electron app on Windows. On Mac it was working fine

**Comment by beligatclement** [comment]
Is there documentation explaining how to use a local version of the plugin to do my tests? Thx @jepiqueau

**Comment by jepiqueau** [comment]
@beligatclement not really what i do myself to test the electron part of the plugin is to make the modification on my local copy of the plugin build the electron part and copy the dist folder into the application both on the node_modules/@capacitor-community/sqlite/electron and also in the electron/node_modules/@capacitor-community/sqlite/electron you have to remove the dist folder prior in both mentioned folders. You must not run a npx cap sync @capacitor-community/electron otherwise it will erase the modification.

**Comment by jepiqueau** [comment]
@beligatclement after this you run npm run build and npx cap copy @capacitor-community/electron and cd electron and npm run electron:start

**Comment by beligatclement** [comment]
@jepiqueau 
I found different behavior between android/ios and electron. On android/ios when I call `createConnection(dbName, true, "secret", 1)` without having done a `setEncryptionSecret` before, it does not encrypt the database, unlike the electron code which I uncommented (with the default pssphrase). What is the desired behavior?

**Comment by jepiqueau** [comment]
@beligatclement i think the behaviour should be the same for all platforms. This is what i try to achieve.

**Comment by jepiqueau** [comment]
@beligatclement Did you finalize the testing ?

**Comment by beligatclement** [comment]
@jepiqueau I have package my app for windows and linux with electron-packager 17.1.1 and it was working as intended.
I would still be more confident if someone else could test it. I was not able to test all of the features within my project.

Concerning the proofreading of the code I could forget certain modifications not knowing the project specifically.

**Comment by jakemitchellxyz** [comment]
@jepiqueau @beligatclement Let's try to get this in asap, what's the status? I need this for a project, I can help test if necessary

**Comment by jepiqueau** [comment]
@beligatclement @jakemitchellxyz i just release a beta release using better-sqlite3 for both database no-encryption and encryption.
npm i --save @capacitor-community/sqlite@better

when in the electron folder of your app
npm install --save better-sqlite3-multiple-ciphers
npm install --save electron-json-storage
npm install --save jszip
npm install --save node-fetch@2.6.7
npm install --save-dev @types/better-sqlite3
npm install --save-dev @types/electron-json-storage

the passphrase is now stored using electron-json-storage  in the defaultDataPath
ie for Mac  'Library/Application Support/YOUR_APP_NAME/storage/userData.json

**Comment by jepiqueau** [comment]
@beligatclement @jakemitchellxyz Can you please test it and revert to me

**Pull request merged**
