### PR TITLE
feat: Database incremental upgrade

### PR DESCRIPTION
**Pull request by dragermrb**
> **Warning**
> This is a large and breaking changes pull request. Please read full description to fully understand.

## Goal

- Transform database upgrade proccess into an incremental process, based on a list of incremental changes on every new database version.
- Simplify plugin upgrade logic, allowing developers to define upgrade logic.

## Proposal

I would like to propose an incremental database upgrade process, based on a list of statements per version, which is executed on the result of the previous version. This approach is similar to Laravel and Doctrine migrations.

This list of statements, designed by the developer, can make modifications, insertions, deletions or updates on the current database, without the plugin having to know the common fields between updates, this responsibility lies with the developer.

For example, we can define the following versions:

```js
const version1 = {
  toVersion: 1,
  statements: [
    `CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY NOT NULL,
        email TEXT UNIQUE NOT NULL,
        name TEXT
    );`,
    `CREATE TABLE messages (
        id INTEGER PRIMARY KEY NOT NULL,
        userid INTEGER,
        title TEXT NOT NULL,
        body TEXT NOT NULL,
        FOREIGN KEY (userid) REFERENCES users(id) ON DELETE SET DEFAULT
    );`,
  ],
};

// This statements are execute over last version database (1), only needs to specify new changes
const version2 = {
  toVersion: 2,
  statements: [`ALTER TABLE users ADD COLUMN age INTEGER;`],
};

// This statements are execute over last version database (2), only needs to specify new changes
const version3 = {
  toVersion: 3,
  statements: [`UPDATE users SET name = 'Guest' WHERE name IS NULL;`],
};
```

In this sample:

- Version `1` will create database schema.
- Version `2` will add a new field over version `1` database.
- Version `3` will update data over version `2`.

## Why

Currently, the database upgrade process is very complex. The plugin must make copies of the existing tables, create the new tables and try to understand the fields that are common between versions to copy the data.

This logic means that adding a single field to a table involves making a copy of the rest of the tables, finding the common fields, creating all the tables again, and copying the existing data. So much overhead.

On the other hand, suppose we want to modify a field as double the current value. With the current logic, you would have to redo the entire database and update the desired field with a query in the `SET` option.

With the proposed approach, the overhead of data transfer is drastically reduced.

## How (code changes)

Summary of code changes

- Remove `fromVersion` and `set` options.
- Refactor `statement:string` to `statements:string[]`.
- Move database file backup outside `onUpgrade()`.
- Add execute statements inside transaction logic.
- Remove backup tables, find common columns, copy data and execute sets logic.

## Plugin new openDB process flow (only if currentVersion and targetVersion differs)

- Backup the current version file backup-YOUR_DB_NAME
- For each version between `currentVersion` and `targetVersion`
  - Starts transaction
  - Execute version statements
  - Commit transaction
  - Update database version
- If process failed, restore the backup file
- Delete the backup file

## Upgrade guide (to be included on documentation)

Since this PR introduces breaking changes, it is necessary to update the application code as follows:

- For each version of the database
  - Remove `fromVersion` field
  - Rename `statement` field to `statements` and convert the string to an array of strings (`string[]`), each of which is a single statement ending in `;`.
  - Convert `set` array (`capSQLiteSet[]`) to string array (`string[]`) and add every item to field `statements`.
  - Remove `set` field.

### Sample

Original upgrade statements array:

```javascript
const upgradeStatements = [
  {
    fromVersion: 1,
    toVersion: 2,
    statement:
      `CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY NOT NULL,
        email TEXT UNIQUE NOT NULL,
        name TEXT,
        age INTEGER,
        last_modified INTEGER DEFAULT (strftime('%s', 'now'))
      );
      CREATE INDEX IF NOT EXISTS users_index_name ON users (name);
      CREATE INDEX IF NOT EXISTS users_index_last_modified ON users (last_modified);
      CREATE TRIGGER IF NOT EXISTS users_trigger_last_modified
        AFTER UPDATE ON users
        FOR EACH ROW WHEN NEW.last_modified <= OLD.last_modified
        BEGIN
            UPDATE users SET last_modified= (strftime('%s', 'now')) WHERE id=OLD.id;
        END;`,
    set: [
      {
        statement: 'INSERT INTO users (name,email,age) VALUES (?,?,?);',
        values: [
          ['Whiteley', 'whiteley@local.host', 30],
          ['Jones', 'jones@local.host', 44],
        ],
      },
    ],
  },
];
```

New upgrade statements array:

```javascript
const upgradeStatements = [
  {
    toVersion: 2,
    statements: [
      `CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY NOT NULL,
        email TEXT UNIQUE NOT NULL,
        name TEXT,
        age INTEGER,
        last_modified INTEGER DEFAULT (strftime('%s', 'now'))
      );`,
      `CREATE INDEX IF NOT EXISTS users_index_name ON users (name);`,
      `CREATE INDEX IF NOT EXISTS users_index_last_modified ON users (last_modified);`,
      `CREATE TRIGGER IF NOT EXISTS users_trigger_last_modified
        AFTER UPDATE ON users
        FOR EACH ROW WHEN NEW.last_modified <= OLD.last_modified
        BEGIN
            UPDATE users SET last_modified= (strftime('%s', 'now')) WHERE id=OLD.id;
        END;`,

      // Sets as individual statements with data
      `INSERT INTO users (name,email,age) VALUES ('Whiteley', 'whiteley@local.host', 30);`,
      `INSERT INTO users (name,email,age) VALUES ('Jones', 'jones@local.host', 44);`,
    ],
  },
];
```

Diff changes

```diff
 const upgradeStatements = [
   {
-    fromVersion: 1,
     toVersion: 2,
-    statement:
+    statements: [
       `CREATE TABLE IF NOT EXISTS users (
         id INTEGER PRIMARY KEY NOT NULL,
         email TEXT UNIQUE NOT NULL,
         name TEXT,
         age INTEGER,
         last_modified INTEGER DEFAULT (strftime('%s', 'now'))
-      );
-      CREATE INDEX IF NOT EXISTS users_index_name ON users (name);
-      CREATE INDEX IF NOT EXISTS users_index_last_modified ON users (last_modified);
-      CREATE TRIGGER IF NOT EXISTS users_trigger_last_modified
+      );`,
+      `CREATE INDEX IF NOT EXISTS users_index_name ON users (name);`,
+      `CREATE INDEX IF NOT EXISTS users_index_last_modified ON users (last_modified);`,
+      `CREATE TRIGGER IF NOT EXISTS users_trigger_last_modified
         AFTER UPDATE ON users
         FOR EACH ROW WHEN NEW.last_modified <= OLD.last_modified
         BEGIN
             UPDATE users SET last_modified= (strftime('%s', 'now')) WHERE id=OLD.id;
         END;`,
-    set: [
-      {
-        statement: 'INSERT INTO users (name,email,age) VALUES (?,?,?);',
-        values: [
-          ['Whiteley', 'whiteley@local.host', 30],
-          ['Jones', 'jones@local.host', 44],
-        ],
-      },
+
+      // Sets as individual statements with data
+      `INSERT INTO users (name,email,age) VALUES ('Whiteley', 'whiteley@local.host', 30);`,
+      `INSERT INTO users (name,email,age) VALUES ('Jones', 'jones@local.host', 44);`,
     ],
   },
 ];
```

### CODE REVIEW

**Comment by jepiqueau** [comment]
@dragermrb seems to be a great contribution is this mile the migrations in typeOrm ? Do you store in a migration database all the command lines for each version allowing for decreasing/increasing version. I have no time to look at it right now. I am currently refurbishing a house which takes all my time. May be mid of July i will have a look can you also provide examples where it is used so itwill be easy for me to het in.

**Comment by jepiqueau** [comment]
@dragermrb to get in

**Comment by dragermrb** [comment]
Hi @jepiqueau

I was not aware of the use of TypeORM. The idea of this PR is similar to TypeORM migrations, but using only the `addUpgradeStatement(...)` method of the API (does not include reverting migrations).

- If a user is already using TypeORM migrations, they should not use `addUpgradeStatement()` and therefore this PR is useless to them.
- If a user is using `addUpgradeStatement()`, this PR would change how updates are applied to the database.

In my apps, I have an array with all the migrations defined and I apply it with `addUpgradeStatement()`.

```typescript
let upgrades = [
    {
      toVersion: 1,
      statements: [
        "CREATE TABLE ... ;",
        "CREATE TABLE ... ;",
        "CREATE TABLE ... ;",
        // ...
      ]
    },
    {
      toVersion: 2,
      statements: [
        "CREATE TABLE ... ;",
        "CREATE TABLE ... ;",
        "CREATE TABLE ... ;",
        // ...
      ]
    },
];

let result:any = await this._SQLiteService.addUpgradeStatement(
  "test-sqlite",
  upgrades
);
result = await this._SQLiteService.openDB("my-database", false, "no-encryption", 2);
```

**Comment by jepiqueau** [comment]
@dragermrb i am starting looking at this It would be nice if you provide a simple app to demonstrate this that i could use to replace the testupgradeversion in angular-sqlite-app-starter

**Comment by dragermrb** [comment]
Hi @jepiqueau 

Sorry for not replying sooner, it's been a busy summer.

I'm going to try to prepare an app-demo for next week.

**Comment by jepiqueau** [comment]
@dragermrb i am going to merge it and will look at the modifications in `angular-sqlite-app-starter` if i have an issue i will ask you to look at it avoiding you to loose your time to create an app

**Comment by jepiqueau** [comment]
@dragermrb  
When you said this
```
let upgrades = [
    {
      toVersion: 1,
      statements: [
        "CREATE TABLE ... ;",
        "CREATE TABLE ... ;",
        "CREATE TABLE ... ;",
        // ...
      ]
    },
    {
      toVersion: 2,
      statements: [
        "CREATE TABLE ... ;",
        "CREATE TABLE ... ;",
        "CREATE TABLE ... ;",
        // ...
      ]
    },
];

let result:any = await this._SQLiteService.addUpgradeStatement(
  "test-sqlite",
  upgrades
);
result = await this._SQLiteService.openDB("my-database", false, "no-encryption", 2);
```
can you provide the service for addUpgradeStatement
i thought for version 1 it would have been
let result:any = await this._SQLiteService.addUpgradeStatement(
  "test-sqlite",
  upgrades[0].toVersion, upgrades[0].statements
);
and for version 2
let result:any = await this._SQLiteService.addUpgradeStatement(
  "test-sqlite",
  upgrades[1].toVersion, upgrades[1].statements
);
if i do this with the old service it works for Android and iOS but not for Electron

Are you recreating the whole database each time you want to upgrade a version ?
In that case what happens to the data created in the session?
Can you answer quickly

**Comment by dragermrb** [comment]
> 
> i thought for version 1 it would have been let result:any = await this._SQLiteService.addUpgradeStatement( "test-sqlite", upgrades[0].toVersion, upgrades[0].statements ); and for version 2 let result:any = await this._SQLiteService.addUpgradeStatement( "test-sqlite", upgrades[1].toVersion, upgrades[1].statements );

Correct!

> 
> Are you recreating the whole database each time you want to upgrade a version ? In that case what happens to the data created in the session? Can you answer quickly

You have to add the upgrade statements every time you starts the app, before open database.

Later, when you open the database, the plugin first read database version (with `CapacitorSQLite.getVersion(string)` for android or with `Database.getVersion()` for ios) and only applies upgrades above `currentDatabaseVersion`.

So, the first time you open the database all upgrade statements are applied, but the second and subsequent times none are applied (they are already applied).

Maybe later you will release a new version of the app that has a new upgrade statement. In this case, when you start the app, only the latest upgrade statement is applied, since the previous ones have already been applied.

**Comment by jepiqueau** [comment]
@dragermrb  your implementation it is not really working like this if you look SQLiteConnection in definition.ts
```
  async addUpgradeStatement(
    database: string,
    toVersion: number,
    statements: string[],
  ): Promise<void> {
    const upgrade: capSQLiteVersionUpgrade = {
      toVersion,
      statements,
    };
    try {
      if (database.endsWith('.db')) database = database.slice(0, -3);
      await this.sqlite.addUpgradeStatement({
        database,
        upgrade: [upgrade],
      });
      return Promise.resolve();
    } catch (err) {
      return Promise.reject(err);
    }
  }

```
upgrade is not an array and contains only one value of toVersion and statements

**Comment by dragermrb** [comment]
Hi @jepiqueau 

This code will call `SQLiteConnection.addUpgradeStatement()` method from `definitions.ts`

```ts
let result:any = await this._SQLiteService.addUpgradeStatement(
    "test-sqlite",
    upgrades[0].toVersion, // number
    upgrades[0].statements // array 
);
```

**File `src/definitions.ts`, line 1076**

```ts
async addUpgradeStatement(
    database: string,
    toVersion: number,
    statements: string[],
): {
    const upgrade: capSQLiteVersionUpgrade = {
      toVersion,
      statements,
    };
    //...
    await this.sqlite.addUpgradeStatement({
        database,
        upgrade: [upgrade],
      }); // ================> this call is implemented on Android, IOS or Electron
    //...
  }
```

Implementation of `addUpgradeStatement()` on native platforms (Android, Ios, Electron) expects to receive `database` (string) and `upgrade` (object {toVersion,statements}) params. 

**File `android/src/main/java/com/getcapacitor/community/database/sqlite/CapacitorSQLitePlugin.java`, line 1182**

```java
public void addUpgradeStatement(PluginCall call) {
    if (!call.getData().has("database")) {
        String msg = "AddUpgradeStatement: Must provide a database name";
        rHandler.retResult(call, null, msg);
        return;
    }
    String dbName = call.getString("database");
    if (!call.getData().has("upgrade")) {
        String msg = "AddUpgradeStatement: Must provide an array with upgrade statement";
        rHandler.retResult(call, null, msg);
        return;
    }
    JSArray upgrade = call.getArray("upgrade");

    // ...
}
```

**File `ios/Plugin/CapacitorSQLite.swift`, line 1142**

```swift
@objc func addUpgradeStatement(_ dbName: String, upgrade: [[String: Any]]) throws -> [Int: [String: Any]] {
    // ...

    if !(keys.contains("toVersion")) || !(keys.contains("statements")) {
        var msg: String = "upgrade must have keys in "
        msg.append("{toVersion,statements}")
        throw CapacitorSQLiteError.failed(message: msg)
    }

    // ...
}
```
**File `electron/src/index.ts`, line 477**

```ts
async addUpgradeStatement(options: capSQLiteUpgradeOptions): Promise<void> {
    const dbName: string = this.getOptionValue(options, 'database');
    const upgrades: capSQLiteVersionUpgrade[] = this.getOptionValue(
      options,
      'upgrade',
    );

    // ...

    if (
      !versionUpgradeKeys.includes('toVersion') ||
      !versionUpgradeKeys.includes('statements')
    ) {
      throw new Error('Must provide an upgrade capSQLiteVersionUpgrade Object');
    }
    
    // ...
}
```
        
Isn't that correct??

**Comment by jepiqueau** [comment]
@dragermrb 
```
let result:any = await this._SQLiteService.addUpgradeStatement(
    "test-sqlite",
    upgrades[0].toVersion, // number
    upgrades[0].statements // array 
);
```
will always take the first element of the upgrades

this is why it is working well when you do
```
... 
      await this._sqlite.addUpgradeStatement("test-updversion",
      upgrades[0.toVersion,upgrades[0].statements);     
...
      await this._sqlite.addUpgradeStatement("test-updversion",
      upgrades[1].toVersion,upgrades[1].statements);     
...
```

but does not work when you do 
```
      await this._sqlite.addUpgradeStatement("test-updversion",
      upgrades);     
```
`Maybe later you will release a new version of the app that has a new upgrade statement. In this case, when you start the app, only the latest upgrade statement is applied, since the previous ones have already been applied.` 
this i cannot see it as you always took upgrade[0].
i am just trying to understand what you have done  as i have to implement it in `jeep-sqlite` stencil component to have the web part of the plugin working.
So the question is why upgrades is now an array of json objects as the command takes a json object as input? is this just to keep them somewhere in the app?

**Comment by jepiqueau** [comment]
@dragermrb i just got the thing publish in 4.1.0-6  you can have a look at the implementation in [angular-sqlite-app-starter](https://github.com/jepiqueau/angular-sqlite-app-starter). Thanks for your contribution it is a lot smarter process.

**Comment by dragermrb** [comment]
> i am just trying to understand what you have done as i have to implement it in `jeep-sqlite` stencil component to have the web part of the plugin working. So the question is why upgrades is now an array of json objects as the command takes a json object as input? is this just to keep them somewhere in the app?

Ok, now I understand you!

The different calls to the `addUpgradeStatement()` method must be made by the user, at the app level, as many times as there are different versions.

This would be an example of code at the app level (I have omitted the error check)


```ts
// Define upgrades
let upgrades = [
    {
      toVersion: 1,
      statements: [
        "CREATE TABLE ... ;",
        "CREATE TABLE ... ;",
        "CREATE TABLE ... ;",
        // ...
      ]
    },
    {
      toVersion: 2,
      statements: [
        "CREATE TABLE ... ;",
        "CREATE TABLE ... ;",
        "CREATE TABLE ... ;",
        // ...
      ]
    },
];

// Create connection
const sqlitePlugin: any = CapacitorSQLite;
let sqlite: SQLiteConnection = new SQLiteConnection(sqlitePlugin);

// Add upgrades statments. This is where the user adds the various upgrades
for (const upgrade of upgrades) {
    // One call per database version
    await sqlite.addUpgradeStatement(
        dbName,
        upgrade.toVersion,
        upgrade.statements
    );
}

// initialize the connection
let db: SQLiteDBConnection = await sqlite.createConnection(
    "my-db-name",
    false,
    "no-encryption",
    CURRENT_SCHEMA_VERSION
);

// open user db
await db.open();
```

**Pull request merged**
