### PR TITLE
feat(android): support project variables

### PR DESCRIPTION
**Pull request by robingenz**
This PR allows specifying the versions of the dependencies on Android.

This should help #199.

### CODE REVIEW

**Comment by jepiqueau** [comment]
@robingenz Can you explain how it will help #199 and if it is required to do this. It seems interesting but i would like to understand the reasons behind can you help me

**Comment by robingenz** [comment]
@jepiqueau Sure! This feature allows you to set the version of the Android dependency yourself.

Example: https://github.com/capacitor-community/sqlite/issues/199#issuecomment-992626461

You can set `androidx.security:security-crypto:1.1.0-alpha03` as default. However, if someone needs `androidx.security:security-crypto:1.0.0`, then they can add the following to the `variables.gradle` file:

```diff
ext {
+    androidxSecurityCryptoVersion = '1.0.0'
}
```

**Comment by jepiqueau** [comment]
@robingenz ok but how in the code i can test which crypto version has been selected to switch for the right code as there are some new features in 1.1.0-alpha03 not compatible with 1.0.0 ?

**Comment by jepiqueau** [comment]
@robingenz in fact i tested using the 1.0.0 but it is not working with the actual code

**Comment by robingenz** [comment]
@jepiqueau I didn't know you were using a new feature. In that case it does not work as far as I know.

Of course, it can still be helpful if you want to use a different version that is compatible with the plugin for other reasons.
Either way, this change should not hurt.
But it is no problem at all if you reject the PR. 😄

**Comment by jepiqueau** [comment]
@robingenz Thanks for all your explanations, i never though about using project variables. I will reject the PR but thanks again to share some of your knowledge with me this is what i am looking for

**Pull request closed without merging**
