### PR TITLE
Allow copying databases from the cache folder

### LINKED ISSUE #300: Plugin fails to copy from cache folder
**Describe the bug**
When calling `addSqliteSuffix("cache", ...)` the method does not copy the databases from the cache folder in Android
See more info in #61 

**To Reproduce**

1. Save a database in the cache folder
2. Call `addSqliteSuffix`

**Expected behavior**
The database should be copied and it should have the right suffix

**Screenshots**
N/A

**Desktop (please complete the following information):** N/A

- OS: [e.g. iOS] Android
- Browser [e.g. chrome, safari] N/A
- Version [e.g. 22] any

**Smartphone (please complete the following information):**
Any Android device

**Additional context**
The problem is in this file in Android:
https://github.com/capacitor-community/sqlite/blob/26330a3a0b4cfb255755e7b82feb2bcbeb19c791/android/src/main/java/com/getcapacitor/community/database/sqlite/SQLite/UtilsMigrate.java#L79
As it doesn't take into consideration the cache folder.
I don't know about iOS.
I'll send a PR soon.

### PR DESCRIPTION
**Pull request by HarelM**
Fixes #300
I'm still having a hard time testing the github link in my repo due to typescript transpiration, but in general I have tested this to work...

### CODE REVIEW

**Comment by HarelM** [comment]
As a side note, and please don't get me the wrong way as I honestly appreciate all your hard work on this plugin.
The "ifs" in this code are making it very hard to read - the amount of indentation in many places in the code makes it harder to read without debug, and even when debugging sometimes it happens that a part of a code was skipped and I didn't understand why due to the strong indentation.
For a better explanation of what I'm talking about see here:
https://dev.to/zachsnoek/clean-up-your-code-by-removing-unneeded-indentation-3g9i#:~:text=Clean%20up%20your%20code%20by%20removing%20unneeded%20indentation%20%F0%9F%A7%B9,-%23programming%20%23javascript%20%23&text=Indenting%20code%2C%20while%20usually%20not,of%20code%20harder%20to%20read.

**Comment by HarelM** [comment]
I've also fixed iOS now after testing it in my app

**Comment by jepiqueau** [comment]
@HarelM How do you call it in addSQLiteSuffix you should change this method too ?

**Comment by HarelM** [comment]
Thanks! let me know when a new version is available :-)

**Comment by jepiqueau** [comment]
@HarelM you did not answer my question. How does it change addSQLitePrefix ot how did you test it this will help me to add a test before release it

**Comment by HarelM** [comment]
Simply call the method with `addSQLitePrefix('cache', ...)` or `addSQLitePrefix('Cache', ...)` or `addSQLitePrefix('CACHE', ...)`.
Sorry, must have missed that question...

**Comment by jepiqueau** [comment]
@HarelM OK thank you.i will have a look. As it os an important feature would be nice if you could provide a complete simple example  to be added in the test of the angular-sqlite-app-starter with a sqlite database available on a remote server reading on the cache  and using addSQLiteSuffix as this could be an alternative to the importFromJson and may have some interest from others developers

**Comment by HarelM** [comment]
I'll see what I can do, sure.

**Pull request merged**
