### PR TITLE
Improve code in docs

### PR DESCRIPTION
**Pull request by fizdalf**
I have updated the Ionic-Angular code for the sqlite.service.ts to remove unnecessary promise wrapping and error handling as all methods are async.

### CODE REVIEW

**Comment by jepiqueau** [comment]
@fizdalf Why did you remove the try...catch means that you will never get back the error?

**Comment by fizdalf** [comment]
The try/catch were catching and the returning a failed promise, but all the
functions are already async, when a function is async it is already wrapped
in a promise so just throwing an error will be processed as a promise
rejection, so they were unnecessary

**Comment by fizdalf** [comment]
Where I say "failed promise", I meant "rejected promise"

**Comment by fizdalf** [comment]
@jepiqueau no probs. We are learning all the time. I see if there's something else I can contribute with.

**Pull request merged**
