### PR TITLE
Code readability improvements

### PR DESCRIPTION
**Pull request by tobiasmuecksch**
I have only changed the readability of the code (platforms `web` and `electron`). It still works exactly the same.

Here's a quick summary of what I did:

- I renamed many variables, so it's faster to see, what the purpose of a variable is (for example `sqliteEl` -> `jeepSqliteElement`).
- I replaced `Promies.reject()` with `throw new Error().` It works exactly the same and is more common. Also this gives us the opportunity to implement custom Exceptions in the future.
- I completely removed `Promise.resolve()`, since it's completely useless in `async`-methods
- [As recommended in the google style guidelines ](https://google.github.io/styleguide/tsguide.html#control-flow-statements-blocks)ALL `if`-block bodies are enclosed with `{ ... }`, because it's more readable and less error-prone
- Improved some error messages.
- I've moved all unimplemented methods to the bottom of the file.
- I've reduced repeating code and moved it into separate methods (for example `getDatabaseConnectionOrThrowError()`)

### CODE REVIEW

**Comment by tobiasmuecksch** [comment]
I haven't reworked all `electron-utils` yet. If you are satisfied with this PR, I'll rework the utils in a separate PR 👍

**Comment by tobiasmuecksch** [comment]
If this PR causes merge conflicts with your current work [regarding the delete method](https://github.com/capacitor-community/sqlite/issues/259#issuecomment-1104815617), I can make a new PR after you committed your changes.

**Comment by jepiqueau** [comment]
@tobiasmuecksch thanks for your contribution thera are part of th 3.4.3-1 release. Before to do new PRs can you wait that i complete the delete command  which brings big changes in the code it will be easier for me to manage. Thanks for your understanding

**Comment by tobiasmuecksch** [comment]
Sure, I'll wait 😃 👍

**Pull request merged**
